build:
  nodes:
    analysis:
      tests:
        override:
          - pylint-run --rcfile=.pylint.ini
          - py-scrutinizer-run
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - "*/tests/*"
    - "*/static/js/*min.js"
