site_name: Flask API

pages:
  - Home: index.md
  - API Guide:
    - Renderers: api-guide/renderers.md
    - Parsers: api-guide/parsers.md
    - Templates: api-guide/templates.md
    - Exceptions: api-guide/exceptions.md
    - Status Codes: api-guide/status-codes.md
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

repo_url: https://github.com/flask-api/flask-api
copyright: '<a href="/about/license">BSD licensed</a> <b>&middot;</b> Copyright &copy; 2017, <a href="https://twitter.com/_tomchristie">Tom Christie</a>.'
